### ISSUE TITLE
Great HTMl

### ISSUE THREAD

**Issue by Rodrigap** [narokoe/prj-rev-bwfs-dasmoto#1]
https://github.com/narokoe/prj-rev-bwfs-dasmoto/blob/f663c76c9feb05688e9ef534d4e295920d9880f2/DasmotosArts/index.html#L25-L34

I love how organized and neat your HTML is! It's a really good thing to get into the habit of adding comments to separate your HTML sections. Keep this up!

**Comment by narokoe** [comment]
I took note of how organized it was in one of the lessons and instantly fell in love with it.  It makes it so much easier to easily navigate the code.  I wanted to make sure I incorporated it into my own code.  Thank you for noticing!
