### ISSUE TITLE
Minor: Indentation

### ISSUE THREAD

**Issue by Rodrigap** [narokoe/prj-rev-bwfs-dasmoto#2]
https://github.com/narokoe/prj-rev-bwfs-dasmoto/blob/f663c76c9feb05688e9ef534d4e295920d9880f2/DasmotosArts/index.html#L38-L45

Take a look at this section and notice how your first line and second line are on the same level; neither is nested within the other, so they should have the same indentation! I was confused at first and thought you might be missing closing div tags because of the implication that this indentation gives. Should be like this:

   ```
      <div id="paint">Paint</div>
      <div>
        <br />
        <br />
        <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/finnish.jpeg" alt="paint on wooden table">
        <h3>Clean Finnish Paint</h3>
        <p>Imported paint from Finland. Over 256 colors available in-store, varying in quantity (1 oz. to 8 oz.). Clean Finnish paint microbinds to canvas, increasing the finish and longevity of any artwork. <span class="pricing">Starting at $5.00 / tube.</span></p>
      </div>
```

**Comment by narokoe** [comment]
Ok, that makes total sense.  Thank you!  I feel like I use a lot of commas in my every day typing and I can feel a very similar need to use indents a lot in code.  I'll make a mental note. :)
