### ISSUE TITLE
Nice use of universal styling

### ISSUE THREAD

**Issue by Rodrigap** [narokoe/prj-rev-bwfs-dasmoto#3]
https://github.com/narokoe/prj-rev-bwfs-dasmoto/blob/f663c76c9feb05688e9ef534d4e295920d9880f2/DasmotosArts/resources/style.css#L2-L5

Good job remembering to use universal styling! It eliminates a lot of code repetition

**Comment by narokoe** [comment]
I was pretty proud of remembering that one!  It didn't start like that, but after I typed 'Helvetica' the third time it hit me like a sack of bricks that there was a better way.
