### ISSUE TITLE
Grade: Meets Expectations

### ISSUE THREAD

**Issue by Rodrigap** [narokoe/prj-rev-bwfs-dasmoto#4]
Great job with this project! Your HTML and CSS are both really concise and organized, and your finished product looks just like the spec. I especially love the comments you added in your HTML, you could consider adding matching comments in your CSS as well. My only critique was to pay attention to your HTML indentations. Other than that, your code looks great! Remember that you can always elaborate on the spec if you're feeling creative. Feel free to add extra colors/fonts/styling elements

**Comment by narokoe** [comment]
Thank you!  I will take a peek at my html indentation note and remember for future reference. :)
